// PACE local bot — generated by tools/build.mjs from src/. Do not edit.
(() => {
'use strict';
// ---- src/controller.mjs
// Deterministic baseline only. Browser adapter and latency compensation are separate.
function speedCap(x) {
  const p = Math.max(0, x);
  const q = Math.max(0, p - 24) / 12;
  return 1.5 + 1.74 * (.08 * -Math.expm1(-p / 12) + .92 * -Math.expm1(-(q*q)));
}

function decide(obs, { mode = 'cash', held = false, history = [] } = {}) {
  if (!['cash', 'win'].includes(mode)) throw new Error('Unknown objective');
  if (!obs || obs.phase !== 'running' ||
      ![obs.t, obs.safety, obs.own?.position, obs.own?.speed,
        obs.opponent?.deployed].every(Number.isFinite) || obs.own.speed < 0) {
    return { held: false, reason: 'invalid or inactive observation' };
  }
  let slope = 0;
  for (let i = history.length - 1; i >= 0; --i) {
    const h = history[i];
    if (Number.isFinite(h.t) && Number.isFinite(h.safety) && obs.t - h.t >= .5 - 1e-6) {
      slope = Math.max(0, (obs.safety - h.safety) / (obs.t - h.t));
      break;
    }
  }
  const stop = obs.own.position + obs.own.speed ** 2 / (2 * .62 * speedCap(obs.own.position));
  const forecast = mode === 'win' ? 1 : .5;
  const target = Math.max(obs.opponent.deployed, obs.safety - .1 + Math.min(2, forecast * slope));
  const next = stop < target - (held ? 0 : .3);
  return { held: next, reason: next ? 'headroom' : 'braking', stop, target, slope };
}

// ---- src/policy.mjs
// Pure policy functions over player-visible observations. No browser or engine access.
// Observation shape (all numbers finite unless noted):
//   { t, phase: 'running'|..., safety, own: { position, speed, deployed }, opponent: { deployed } }
// history: [{ t, safety }] of past observed frontier samples, oldest first.


const ACCEL = .62;
const DT = 1 / 60;

function stopDistance(x, v) {
  return v * v / (2 * ACCEL * speedCap(x));
}

// Advance own research under the original movement law (trapezoid, per-frame cap), for `steps` frames.
function project(x, v, held, steps) {
  for (let i = 0; i < steps; i++) {
    const V = speedCap(x);
    if (held) {
      const nv = Math.min(V, v + ACCEL * V * DT);
      x += (v + nv) / 2 * DT; v = nv;
    } else {
      const a = ACCEL * V, tt = Math.min(DT, v / a), nv = Math.max(0, v - a * DT);
      x += (v + nv) / 2 * tt; v = nv;
    }
  }
  return { x, v };
}

function validObservation(obs) {
  return !!obs && obs.phase === 'running' &&
    [obs.t, obs.safety, obs.own?.position, obs.own?.speed, obs.opponent?.deployed].every(Number.isFinite) &&
    obs.own.speed >= 0;
}

function frontierSlope(obs, history, window = .5) {
  for (let i = history.length - 1; i >= 0; --i) {
    const h = history[i];
    if (Number.isFinite(h.t) && Number.isFinite(h.safety) && obs.t - h.t >= window - 1e-6)
      return Math.max(0, (obs.safety - h.safety) / (obs.t - h.t));
  }
  return 0;
}

const PRESETS = {
  // Production presets, tuned on training seeds (LCG indices 0..599) under the practice timing model
  // (15 Hz snapshots, decision on arrival). `lookahead` is one decision interval in frames.
  cash: { forecast: .25, maxLead: 2, offset: -.3, matchOpponent: true, oppLead: 0, hysteresis: .1, horizon: 0, lookahead: 4 },
  win: { forecast: 1, maxLead: 2, offset: -.1, matchOpponent: true, oppLead: 0, hysteresis: .1, horizon: 0, lookahead: 4 },
  // Handoff reproduction family (described as 5 Hz in the original benchmark).
  'repro-cash': { forecast: .5, maxLead: 2, offset: -.1, matchOpponent: true, oppLead: 0, hysteresis: .3, horizon: 0, lookahead: 0 },
  'repro-win': { forecast: 1, maxLead: 2, offset: -.1, matchOpponent: true, oppLead: 0, hysteresis: .3, horizon: 0, lookahead: 0 },
};

// Generalized target-tracking controller. With horizon=0 and a preset it is the handoff baseline;
// horizon>0 is the latency-compensated variant: it projects own state forward `horizon` frames under
// the last issued control (observation/delivery delay), then asks whether holding for one more
// decision interval (`lookahead` frames) would still leave a stop point below target.
function decideTarget(obs, { params = PRESETS.cash, held = false, history = [], lookahead } = {}) {
  if (!validObservation(obs)) return { held: false, reason: 'invalid or inactive observation' };
  const p = { ...PRESETS.cash, ...params };
  lookahead ??= p.lookahead;
  const slope = frontierSlope(obs, history);
  let { position: x, speed: v } = obs.own;
  if (p.horizon > 0) ({ x, v } = project(x, v, held, Math.round(p.horizon)));
  const target = Math.max(p.matchOpponent ? obs.opponent.deployed + p.oppLead : -Infinity,
    obs.safety + p.offset + Math.min(p.maxLead, p.forecast * slope));
  let stop;
  if (lookahead > 0) {
    const f = project(x, v, true, Math.round(lookahead));
    stop = f.x + stopDistance(f.x, f.v);
  } else stop = x + stopDistance(x, v);
  const next = stop < target - (held ? 0 : p.hysteresis);
  return { held: next, reason: next ? 'headroom' : (stop >= target ? 'braking: stop point at target' : 'waiting: hysteresis'), stop, target, slope };
}

// Offline baselines.
function decideSafeFrontier(obs, { offset = 0, held = false, hysteresis = .3 } = {}) {
  if (!validObservation(obs)) return { held: false, reason: 'invalid' };
  const stop = obs.own.position + stopDistance(obs.own.position, obs.own.speed);
  return { held: stop < obs.safety + offset - (held ? 0 : hysteresis), reason: 'frontier', stop, target: obs.safety + offset };
}

// The official CPU rule, evaluated on our own visible observation.
function decideCpuMirror(obs, { held = false } = {}) {
  if (!validObservation(obs)) return { held: false, reason: 'invalid' };
  const behind = obs.own.deployed < obs.opponent.deployed;
  const target = Math.max(obs.safety, behind ? obs.opponent.deployed + 1.5 : 0);
  const stop = obs.own.position + stopDistance(obs.own.position, obs.own.speed);
  return { held: stop < target - (held ? 0 : .3), reason: 'cpu mirror', stop, target };
}

function decideAlways(obs) {
  return { held: validObservation(obs), reason: 'always' };
}


// ---- src/competitive.mjs
// Online policy: infer opponent motion from visible deployed research, then choose a
// profit/risk target. Constants/formulas match the verified public PACE engine.


const DEPLOYMENT_SECONDS = 2;
const ACCELERATION_END = 90;
const YEARS_PER_SECOND = 7 / 365;
const COMPETITIVE_PRESETS = {
  leaderboard: { forecast: 1, opponentForecast: 3, wealth: 1, winWeight: .25,
    opponentModel: 'anchored', maxTargetGap: 2, motionModel: 'pending',
    catchupToDeployed: true, endgameSeconds: 6, endgameForecast: DEPLOYMENT_SECONDS, deadlineAware: true },
  competitive: { forecast: 1.5, opponentForecast: 3, wealth: 1, winWeight: .5 },
};

function annualProfit(own, opponent) {
  const base = 5e9 + 1e10 * Math.log1p(.025 * Math.max(0, own));
  const lead = own - opponent;
  if (lead >= 0) return base + 3e9 * Math.log1p(lead / 2);
  const lag = -lead, discounted = base / (1 + .4 * Math.log1p(lag / 2));
  const z = Math.log(lag) + (opponent - 22) / 4;
  const softplus = Math.max(0, z) + Math.log1p(Math.exp(-Math.abs(z)));
  const competitive = (discounted + 8e9) / (1 + softplus) - 8e9;
  const u = Math.min(1, lag / 2), blend = u * u * (3 - 2 * u);
  return discounted + (competitive - discounted) * blend;
}

function catastropheRate(deployed, safety) {
  const x = Math.max(0, deployed), gap = Math.max(0, x - safety);
  if (!x || !gap) return 0;
  return .24 / (1 + (12 / x) ** 2) / (1 + 75 / (gap * gap));
}

function opponentSpeed(obs, history, window = .75) {
  for (let i = history.length - 1; i >= 0; i--) {
    const h = history[i], dt = obs.t - h.t;
    if (dt >= window - 1e-6 && Number.isFinite(h.opponent))
      return Math.max(0, Math.min(speedCap(obs.opponent.deployed), (obs.opponent.deployed - h.opponent) / dt));
  }
  return 0;
}

function decideCompetitive(obs, { held = false, history = [], lookahead = 5, delayFrames = 0, pendingFrames = 0, params = {} } = {}) {
  if (!validObservation(obs) || ![obs.own.cash, obs.own.deployed, obs.opponent.cash].every(Number.isFinite))
    return { held: false, reason: 'invalid or inactive observation' };
  const { forecast = 2, opponentForecast = 2, lead = 0, wealth = 1, winWeight = 0, hysteresis = .08,
    opponentModel = 'bounded', maxTargetGap = Infinity, motionModel = 'issued',
    catchupToDeployed = false, endgameSeconds = 0, endgameForecast = forecast, deadlineAware = false } = params;
  const slope = frontierSlope(obs, history);
  const velocity = opponentSpeed(obs, history);
  // Ramp toward a settlement-aware frontier forecast near the finish. Only past
  // observations are used; an unseen plateau can still invalidate this forecast.
  const endgameBlend = endgameSeconds > 0 ? Math.max(0, Math.min(1, (obs.t - ACCELERATION_END + endgameSeconds) / endgameSeconds)) : 0;
  const forecastSeconds = forecast + endgameBlend * (endgameForecast - forecast);
  const predictedSafety = obs.safety + Math.min(3, forecastSeconds * slope);
  const gaps = history.filter(h => h.t <= obs.t && obs.t - h.t <= 2 && Number.isFinite(h.opponent)).map(h => h.opponent - h.safety).sort((a, b) => a - b);
  const gap = gaps.length ? gaps[Math.floor(gaps.length / 2)] : obs.opponent.deployed - obs.safety;
  // Deployment speed oscillates as players tap the accelerator. Leaderboard uses the
  // recent frontier offset through brief pauses; Win-focused retains the v0.2 forecast.
  const anchor = obs.safety + Math.min(3, opponentForecast * slope) + gap;
  const prediction = opponentModel === 'anchored' ? anchor : Math.min(
    obs.opponent.deployed + Math.min(4, opponentForecast * velocity), anchor);
  const predictedOpponent = Math.max(obs.opponent.deployed, prediction) + lead;
  // Wealth exposed to a catastrophe includes the bank and future earning potential.
  const remaining = Math.max(0, 92 - obs.t - DEPLOYMENT_SECONDS);
  const futureRate = Math.max(1e8, annualProfit(Math.max(obs.safety, obs.own.deployed), predictedOpponent) * YEARS_PER_SECOND);
  const atRisk = wealth * Math.max(5e9, obs.own.cash + futureRate * remaining);
  // Spend less risk defending a cash lead; increase competitive pressure when behind.
  const pressure = winWeight * Math.max(0, Math.min(2, 1 - (obs.own.cash - obs.opponent.cash) / 1e9));
  const floor = Math.max(0, obs.safety - .5);
  // This bounds the research target, not total risk: frontier forecasts can be wrong
  // and already-deployed research cannot be taken back.
  // Catching up to already-visible deployment does not raise the maximum deployed
  // research that drives shared risk. Never grant this exception for a forecast.
  const cap = Math.max(predictedSafety + maxTargetGap, catchupToDeployed ? obs.opponent.deployed : 0);
  const ceiling = Math.min(Math.max(predictedSafety + 6, predictedOpponent + 3), cap);
  let target = floor, best = -Infinity;
  const step = Math.max(.125, (ceiling - floor) / 128);
  for (let x = floor; x <= ceiling + 1e-8; x += step) {
    const profit = annualProfit(x, predictedOpponent);
    const utility = (profit + pressure * (profit - annualProfit(predictedOpponent, x))) * YEARS_PER_SECOND
      - catastropheRate(Math.max(x, predictedOpponent), predictedSafety) * atRisk;
    if (utility > best) { target = x; best = utility; }
  }
  let { position: x, speed: v } = obs.own;
  const activeFrames = Math.max(0, Math.round((ACCELERATION_END - obs.t) * 60));
  const delay = Math.min(Math.max(0, Math.round(delayFrames)), deadlineAware ? activeFrames : Infinity);
  // A command still in transit cannot affect motion at the start of this projection.
  const pending = motionModel === 'pending' && typeof obs.own.held === 'boolean' ? Math.max(0, Math.min(delay, Math.round(pendingFrames))) : 0;
  if (pending) ({ x, v } = project(x, v, obs.own.held, pending));
  ({ x, v } = project(x, v, held, delay - pending));
  const nextFrames = Math.min(Math.max(1, Math.round(lookahead)), deadlineAware ? activeFrames - delay : Infinity);
  const next = project(x, v, true, nextFrames);
  const coastFrames = activeFrames - delay - nextFrames;
  // The engine zeros velocity at 90 seconds; there is no coasting beyond that
  // deadline. Avoid braking for motion that cannot occur, including input delay.
  const deadlineLimited = deadlineAware && coastFrames < next.v / (ACCEL * speedCap(next.x)) * 60;
  const stop = deadlineLimited ? project(next.x, next.v, false, Math.max(0, coastFrames)).x : next.x + stopDistance(next.x, next.v);
  const accelerate = nextFrames > 0 && stop < target - (held ? 0 : hysteresis);
  return { held: accelerate, reason: accelerate ? 'building profitable lead' : 'protecting cash', stop, target, slope,
    predictedOpponent, predictedSafety, opponentSpeed: velocity, delayFrames, atRisk,
    targetCeiling: ceiling, catchup: catchupToDeployed && obs.opponent.deployed > predictedSafety + maxTargetGap,
    endgameBlend, forecastSeconds, deadlineLimited };
}

// ---- src/agent.mjs
// Stateful controller between a snapshot source and an input sink. No DOM access here.
// Keeps authoritative (observed) state, desired action and last issued action separate.


const OBJECTIVES = ['leaderboard', 'competitive', 'cash', 'win', 'repro-cash', 'repro-win'];
const normalizeMatchLimit = n => Math.max(1, Math.min(50, Math.trunc(Number(n)) || 1));

// Allowlisted, player-visible fields only. Nothing else from the snapshot is retained.
function extractObservation(snap) {
  const g = snap?.game, p = snap?.player;
  if (!g || (p !== 0 && p !== 1)) return null;
  const me = g.labs?.[p], op = g.labs?.[1 - p];
  if (!me || !op) return null;
  return {
    match: `${snap.room}:${snap.match}`,
    t: g.t, phase: g.phase, safety: g.safety, hazard: g.hazard,
    own: { position: me.position, speed: me.speed, deployed: me.deployed, held: me.held, cash: me.cash, profit: me.profit, score: g.scores?.[p] ?? null },
    opponent: { deployed: op.deployed, cash: op.cash, profit: op.profit, score: g.scores?.[1 - p] ?? null },
  };
}

const pct = (xs, q) => {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor(q * s.length))];
};
const summarize = xs => ({ n: xs.length, median: pct(xs, .5), p95: pct(xs, .95), p99: pct(xs, .99), max: xs.length ? Math.max(...xs) : null });

class Agent {
  constructor({ objective = 'leaderboard', matchLimit = 1, staleMs = null, traceLimit = 200000, policyParams = null } = {}) {
    this.objective = objective;
    this.policyParams = policyParams ? { ...policyParams } : null;
    this.matchLimit = normalizeMatchLimit(matchLimit);
    this.staleMsOverride = staleMs;
    this.traceLimit = traceLimit;
    this.armed = false;
    this.completed = 0;
    this.results = [];
    this.reason = 'disarmed on load';
    this.trace = [];
    this.stats = { interArrival: [], ackMs: [], ackGame: [], stale: 0, duplicates: 0, outOfOrder: 0, missedIntervals: 0, rejected: 0 };
    this.resetMatch(null);
  }

  resetMatch(match) {
    this.match = match;
    this.history = [];
    this.frameGaps = [];
    this.recentAckGame = [];
    this.lastIssued = false;
    this.lastResync = null;
    this.last = null;          // last accepted observation
    this.lastRecv = null;      // monotonic ms of last accepted snapshot
    this.desired = false;
    this.pending = null;       // issued input awaiting observed effect
    this.decision = null;
    this.endedCounted = false;
    this.participated = false;
    this.paused = false;
    this.freshSnapshots = 0;
  }

  get staleMs() {
    if (this.staleMsOverride) return this.staleMsOverride;
    const p = pct(this.stats.interArrival.slice(-300), .95);
    return Math.max(250, 4 * (p ?? 67));
  }

  log(e) { if (this.trace.length < this.traceLimit) this.trace.push(e); }

  arm(now) {
    if (this.completed >= this.matchLimit) { this.reason = `match limit ${this.matchLimit} reached`; return false; }
    if (['running', 'settling'].includes(this.last?.phase)) this.participated = true;
    this.armed = true; this.reason = 'armed'; this.log({ k: 'arm', now, objective: this.objective });
    return true;
  }

  setMatchLimit(n, now) {
    this.matchLimit = normalizeMatchLimit(n);
    return this.armed && this.completed >= this.matchLimit ? this.disarm(now, `match limit ${this.matchLimit} reached`) : null;
  }

  // Returns the input the adapter must issue (always a release) or null.
  disarm(now, reason = 'user stop') {
    const was = this.armed;
    this.armed = false; this.paused = false; this.freshSnapshots = 0; this.desired = false; this.reason = reason;
    this.log({ k: 'disarm', now, reason });
    return was || this.lastIssued ? this.issue(false, now, reason) : null;
  }

  issue(held, now, reason) {
    this.lastIssued = held;
    this.seq = (this.seq || 0) + 1;
    // Retrying the same command must not restart its acknowledgement timer.
    const retryOf = this.pending?.held === held ? this.pending.seq : null;
    if (retryOf == null) this.pending = { seq: this.seq, held, now, t: this.last?.t ?? null };
    this.log({ k: 'input', now, seq: this.seq, held, t: this.last?.t ?? null, reason, retryOf });
    return { held, seq: this.seq, reason };
  }

  // Called for each snapshot delivered to the game's render boundary.
  onSnapshot(snap, now) {
    const o = extractObservation(snap);
    if (!o) { this.stats.rejected++; return this.armed ? this.disarm(now, 'malformed snapshot') : null; }
    if (o.match !== this.match) { this.resetMatch(o.match); this.log({ k: 'match', now, match: o.match }); }
    if (this.last) {
      // A forfeit can finish at the same game time as the previous running state.
      if (o.t === this.last.t && o.phase === this.last.phase) { this.stats.duplicates++; return null; }
      if (o.t < this.last.t) { this.stats.outOfOrder++; return null; }
    }
    if (this.lastRecv != null) {
      const gap = now - this.lastRecv;
      if (this.paused && gap > this.staleMs) this.freshSnapshots = 0;
      this.stats.interArrival.push(gap);
      if (gap > 2.5 * (pct(this.stats.interArrival.slice(-300), .5) || 67)) this.stats.missedIntervals++;
    }
    if (this.last) {
      this.frameGaps.push(Math.round((o.t - this.last.t) * 60));
      if (this.frameGaps.length > 60) this.frameGaps.shift();
    }
    this.last = o; this.lastRecv = now;
    if (this.armed && ['running', 'settling'].includes(o.phase)) this.participated = true;
    this.history.push({ t: o.t, safety: o.safety, opponent: o.opponent.deployed });
    if (this.history.length > 64) this.history.splice(0, this.history.length - 32);

    // Acknowledge the pending input once the observed held state matches it.
    if (this.pending && o.own.held === this.pending.held) {
      const ms = now - this.pending.now;
      this.stats.ackMs.push(ms);
      if (this.pending.t != null) {
        const dt = o.t - this.pending.t;
        this.stats.ackGame.push(dt);
        if (o.phase === 'running' && dt > 0) {
          this.recentAckGame.push(dt);
          if (this.recentAckGame.length > 40) this.recentAckGame.shift();
        }
      }
      this.log({ k: 'ack', now, seq: this.pending.seq, t: o.t, ms });
      this.pending = null;
    }

    const entry = { k: 'obs', now, objective: this.objective, t: o.t, phase: o.phase, S: o.safety, x: o.own.position, v: o.own.speed,
      dep: o.own.deployed, held: o.own.held, opp: o.opponent.deployed, cash: o.own.cash, oppCash: o.opponent.cash, hz: o.hazard };

    if (o.phase !== 'running') {
      if (['finished', 'crashed'].includes(o.phase) && !this.endedCounted && this.participated) {
        this.endedCounted = true; this.completed++;
        this.results.push({ match: this.match, objective: this.objective, phase: o.phase,
          cash: o.phase === 'crashed' ? 0 : o.own.score ?? o.own.cash,
          opponentCash: o.phase === 'crashed' ? 0 : o.opponent.score ?? o.opponent.cash });
        this.log({ k: 'end', now, phase: o.phase, cash: o.own.cash, oppCash: o.opponent.cash, hazard: o.hazard });
      }
      if (['finished', 'crashed'].includes(o.phase)) { this.paused = false; this.freshSnapshots = 0; }
      this.log(entry);
      if (this.armed && this.completed >= this.matchLimit && ['finished', 'crashed'].includes(o.phase))
        return this.disarm(now, `match limit ${this.matchLimit} reached`);
      if (this.lastIssued) return this.issue(false, now, 'phase ' + o.phase);
      return null;
    }
    if (!this.armed) { this.log(entry); return null; }
    if (this.paused) {
      // Recover from a transient stall only after two advancing snapshots arrive.
      // Explicit Stop, hidden-page and malformed-state disarms never auto-resume.
      if (++this.freshSnapshots < 2) { this.log(entry); return null; }
      this.paused = false; this.freshSnapshots = 0;
      this.log({ k: 'resume', now, reason: 'fresh snapshots restored' });
    }

    const competitive = COMPETITIVE_PRESETS[this.objective] && { ...COMPETITIVE_PRESETS[this.objective], ...this.policyParams };
    const params = PRESETS[this.objective];
    if (!competitive && !params) return this.disarm(now, 'unknown objective');
    // Compensated presets look ahead one observed decision interval (frames between snapshots).
    const cadence = Math.max(1, Math.min(12, pct(this.frameGaps, .5) ?? 5));
    const lookahead = competitive ? cadence : params.lookahead > 0 ? cadence : 0;
    // Ack delay includes waiting for the next snapshot. Subtract half an interval;
    // this is an estimate of observation-to-input effect delay, not an exact RTT.
    const delayFrames = Math.max(0, Math.min(30, (pct(this.recentAckGame, .5) ?? (7 + cadence / 2) / 60) * 60 - cadence / 2));
    const pendingFrames = this.pending?.t != null ? Math.max(0, delayFrames - (o.t - this.pending.t) * 60) : 0;
    const state = { held: this.lastIssued, history: this.history, lookahead };
    const d = competitive ? decideCompetitive(o, { ...state, params: competitive, delayFrames, pendingFrames }) : decideTarget(o, { ...state, params });
    this.decision = d; this.desired = d.held; this.reason = d.reason;
    entry.desired = d.held; entry.look = lookahead; entry.stop = d.stop; entry.target = d.target; entry.slope = d.slope;
    if (competitive) {
      entry.delayFrames = delayFrames; entry.pendingFrames = pendingFrames; entry.predictedOpponent = d.predictedOpponent;
      entry.predictedSafety = d.predictedSafety; entry.opponentSpeed = d.opponentSpeed;
      entry.targetCeiling = d.targetCeiling; entry.catchup = d.catchup;
      entry.endgameBlend = d.endgameBlend; entry.forecastSeconds = d.forecastSeconds; entry.deadlineLimited = d.deadlineLimited;
    }
    this.log(entry);
    if (d.held !== !!this.lastIssued) return this.issue(d.held, now, d.reason);
    return null;
  }

  // Periodic service: staleness, hidden page, and reconciling UI held state with the issued state.
  // uiHeld: the accelerator state the page UI currently shows (null if unknown).
  tick(now, { hidden = false, uiHeld = null } = {}) {
    if (!this.armed) return null;
    if (hidden) return this.disarm(now, 'page hidden');
    if (this.lastRecv != null && this.last?.phase === 'running' && now - this.lastRecv > this.staleMs) {
      this.freshSnapshots = 0;
      if (this.paused) return null;
      this.stats.stale++; this.paused = true; this.desired = false;
      this.reason = `paused: stale state (${Math.round(now - this.lastRecv)} ms)`;
      this.log({ k: 'pause', now, reason: this.reason });
      return this.issue(false, now, this.reason);
    }
    if (this.paused) return null;
    if (uiHeld != null && this.last?.phase === 'running' && uiHeld !== !!this.lastIssued &&
        now - Math.max(this.pending?.now ?? -Infinity, this.lastResync ?? -Infinity) > 50) {
      this.lastResync = now;
      this.log({ k: 'resync', now, uiHeld, want: !!this.lastIssued });
      return this.issue(!!this.lastIssued, now, 'resync UI');
    }
    return null;
  }

  latency() {
    return { snapshotIntervalMs: summarize(this.stats.interArrival), inputAckMs: summarize(this.stats.ackMs),
      inputAckGameSec: summarize(this.stats.ackGame), stale: this.stats.stale, duplicates: this.stats.duplicates,
      outOfOrder: this.stats.outOfOrder, missedIntervals: this.stats.missedIntervals, rejected: this.stats.rejected };
  }

  performance() {
    const games = this.results.length;
    return { games, averageCash: games ? this.results.reduce((sum, r) => sum + r.cash, 0) / games : null,
      wins: this.results.filter(r => r.phase === 'finished' && r.cash > r.opponentCash).length,
      crashes: this.results.filter(r => r.phase === 'crashed').length };
  }
}

// ---- src/replay.mjs
// Continue through the game's normal Play again control, never its network internals.
// One request per completed match; re-check all guards when the delay expires.
class ReplayQueue {
  constructor({ delayMs = 1000 } = {}) {
    this.delayMs = delayMs;
    this.match = null;
    this.due = null;
    this.requested = false;
    this.status = '';
  }

  tick(now, { agent, hidden = false, button = null }) {
    if (this.match !== agent.match) {
      this.match = agent.match; this.due = null; this.requested = false;
    }
    if (!agent.armed || hidden || agent.completed >= agent.matchLimit || !agent.endedCounted ||
        !['finished', 'crashed'].includes(agent.last?.phase)) {
      this.due = null; this.status = ''; return;
    }
    if (this.requested) { this.status = 'waiting for next game'; return; }
    this.due ??= now + this.delayMs;
    if (now < this.due) { this.status = 'next game shortly'; return; }
    // The widget disables this button when disconnected or already ready.
    if (!button?.isConnected || button.disabled || button.getAttribute('aria-disabled') === 'true' ||
        !button.getClientRects().length) {
      this.status = 'waiting for Play again'; return;
    }
    this.requested = true;
    this.status = 'waiting for next game';
    agent.log({ k: 'replay', now, match: this.match, completed: agent.completed, limit: agent.matchLimit });
    button.click();
  }
}

// ---- src/browser.mjs
// Browser adapter: observes snapshots at the pace-game render boundary (showMatch) and operates the
// game's own keyboard handler (Space on the widget host), which applies the app's blocked/phase checks
// before emitting pace:input. Runs in the page's main world.


function install(win = window) {
  if (win.__paceBot) return win.__paceBot;
  const doc = win.document;
  const perf = win.performance;
  const agent = new Agent({ objective: 'leaderboard', matchLimit: 1 });
  const replay = new ReplayQueue();
  const labels = { leaderboard: 'Leaderboard', competitive: 'Win-focused', cash: 'Cash (legacy CPU)', win: 'Win (legacy CPU)', 'repro-cash': 'Repro cash', 'repro-win': 'Repro win' };
  let host = null, patched = false, lastKeySent = null;

  function uiHeld() {
    const b = host?.shadowRoot?.querySelector('#accelerator');
    return b ? b.getAttribute('aria-pressed') === 'true' : null;
  }

  function send(cmd) {
    if (!cmd) return;
    const target = host && host.isConnected ? host : doc.querySelector('pace-game');
    if (!target) return;
    const type = cmd.held ? 'keydown' : 'keyup';
    target.dispatchEvent(new KeyboardEvent(type, { code: 'Space', key: ' ', bubbles: true, cancelable: true, composed: true }));
    lastKeySent = { type, at: perf.now() };
    render();
  }

  function patch() {
    const C = win.customElements.get('pace-game');
    if (!C || patched) return;
    const orig = C.prototype.showMatch;
    if (typeof orig !== 'function') return;
    patched = true;
    C.prototype.showMatch = function (snapshot) {
      const result = orig.apply(this, arguments);
      try {
        host = this;
        send(agent.onSnapshot(snapshot, perf.now()));
        render();
      } catch (e) { agent.log({ k: 'error', now: perf.now(), msg: String(e) }); }
      return result;
    };
  }
  win.customElements.whenDefined('pace-game').then(patch);

  const timer = win.setInterval(() => {
    try {
      const now = perf.now();
      send(agent.tick(now, { hidden: doc.hidden, uiHeld: uiHeld() }));
      replay.tick(now, { agent, hidden: doc.hidden, button: host?.shadowRoot?.querySelector('#again') });
    } catch (e) {
      agent.log({ k: 'error', now: perf.now(), msg: String(e) });
      send(agent.disarm(perf.now(), 'adapter error'));
    }
  }, 16);
  const onHide = () => send(agent.disarm(perf.now(), 'page hidden'));
  doc.addEventListener('visibilitychange', () => { if (doc.hidden) onHide(); });
  win.addEventListener('pagehide', onHide);
  win.addEventListener('keydown', e => {
    if (e.key === 'Escape' && e.isTrusted && agent.armed) send(agent.disarm(perf.now(), 'emergency stop (Esc)'));
  }, true);

  // ---- operator panel ----
  let panel, ui = {};
  function buildPanel() {
    if (panel || !doc.body) return;
    panel = doc.createElement('div');
    panel.id = 'pace-bot-panel';
    const root = panel.attachShadow({ mode: 'open' });
    root.innerHTML = `<style>
      :host{all:initial;position:fixed;right:12px;bottom:12px;z-index:2147483647;font:12px/1.35 ui-monospace,Menlo,monospace}
      .p{background:#111;color:#eee;border:1px solid #444;border-radius:8px;padding:10px;width:270px;box-shadow:0 4px 18px #0006}
      h1{font-size:12px;margin:0 0 6px;display:flex;justify-content:space-between}
      .row{display:flex;justify-content:space-between;gap:8px}.k{color:#999}
      .armed{color:#4ade80}.off{color:#f87171}
      .ctl{display:flex;gap:6px;margin-top:8px;flex-wrap:wrap;align-items:center}
      button,select,input{font:inherit;background:#222;color:#eee;border:1px solid #555;border-radius:4px;padding:3px 6px}
      button.go{background:#14532d}button.stop{background:#7f1d1d;font-weight:bold}
      input{width:40px}.why{margin-top:6px;color:#fbbf24;min-height:1.3em;word-break:break-word}
    </style><div class="p"><h1><span>PACE bot · v0.4</span><span id="st" class="off">DISARMED</span></h1>
      <div class="row"><span class="k">mode</span><span id="mode">no game</span></div>
      <div class="row"><span class="k">input</span><span id="inp">–</span></div>
      <div class="row"><span class="k">state age</span><span id="age">–</span></div>
      <div class="row"><span class="k">input ack (median)</span><span id="dly">–</span></div>
      <div class="row"><span class="k">own / opp cash</span><span id="cash">–</span></div>
      <div class="row"><span class="k">cumulative risk</span><span id="risk">–</span></div>
      <div class="row"><span class="k">matches</span><span id="cnt">0</span></div>
      <div class="row"><span class="k">run cash / game</span><span id="avg">–</span></div>
      <div class="why" id="why"></div>
      <div class="ctl"><button class="go" id="start">Start</button><button class="stop" id="stop">STOP</button>
        <select id="obj">${OBJECTIVES.map(o => `<option value="${o}">${labels[o]}</option>`).join('')}</select>
        <label class="k">limit <input id="lim" type="number" min="1" max="50" value="1"></label>
        <button id="exp">Export trace</button></div></div>`;
    for (const id of ['st', 'mode', 'inp', 'age', 'dly', 'cash', 'risk', 'cnt', 'avg', 'why', 'start', 'stop', 'obj', 'lim', 'exp']) ui[id] = root.getElementById(id);
    ui.start.onclick = () => { agent.arm(perf.now()); render(); };
    ui.stop.onclick = () => send(agent.disarm(perf.now(), 'user stop')) || render();
    ui.obj.onchange = () => { agent.objective = ui.obj.value; render(); };
    ui.lim.onchange = () => { send(agent.setMatchLimit(ui.lim.value, perf.now())); ui.lim.value = agent.matchLimit; render(true); };
    ui.exp.onclick = exportTrace;
    doc.body.appendChild(panel);
    render();
  }
  const fmt = c => Number.isFinite(c) ? `$${(c / 1e9).toFixed(2)}B` : '–';
  let lastRender = 0;
  function render(force) {
    if (!panel) return;
    const now = perf.now();
    if (!force && now - lastRender < 100) return;
    lastRender = now;
    const o = agent.last;
    ui.st.textContent = agent.armed ? agent.paused ? 'PAUSED' : 'ARMED' : 'DISARMED';
    ui.st.className = agent.armed ? 'armed' : 'off';
    ui.mode.textContent = !o ? 'no game' : labels[agent.objective];
    ui.inp.textContent = `issued ${agent.lastIssued ? 'HOLD' : 'release'} · ui ${uiHeld() == null ? '?' : uiHeld() ? 'HOLD' : 'release'}`;
    ui.age.textContent = agent.lastRecv == null ? '–' : `${Math.round(now - agent.lastRecv)} ms (t=${o.t.toFixed(2)}s ${o.phase})`;
    const a = summarize(agent.stats.ackMs.slice(-200));
    ui.dly.textContent = a.median == null ? '–' : `${a.median.toFixed(1)} ms (p95 ${a.p95.toFixed(1)})`;
    ui.cash.textContent = o ? `${fmt(o.own.cash)} / ${fmt(o.opponent.cash)}` : '–';
    ui.risk.textContent = o && Number.isFinite(o.hazard) ? `${(100 * (1 - Math.exp(-o.hazard))).toFixed(3)}%` : '–';
    ui.cnt.textContent = `${agent.completed} / ${agent.matchLimit}`;
    const results = agent.performance();
    ui.avg.textContent = results.games ? `${fmt(results.averageCash)} · ${results.crashes} crashes` : '–';
    const d = agent.decision;
    ui.why.textContent = agent.armed && replay.status ? replay.status :
      agent.armed && !agent.paused && o?.phase === 'running' && d?.target != null ? `${agent.reason} · stop ${d.stop.toFixed(2)} vs target ${d.target.toFixed(2)}` : agent.reason;
    if (ui.obj.value !== agent.objective) ui.obj.value = agent.objective;
  }
  function exportTrace() {
    const blob = new Blob([JSON.stringify(api.export(), null, 1)], { type: 'application/json' });
    const a = doc.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `pace-bot-trace-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 5000);
  }
  if (doc.body) buildPanel(); else doc.addEventListener('DOMContentLoaded', buildPanel);
  win.setInterval(() => render(), 250);

  const api = {
    agent,
    arm: () => { const ok = agent.arm(perf.now()); render(true); return ok; },
    stop: reason => { send(agent.disarm(perf.now(), reason || 'api stop')); render(true); },
    setObjective: o => { if (!OBJECTIVES.includes(o)) throw new Error('unknown objective'); agent.objective = o; render(true); },
    setMatchLimit: n => { send(agent.setMatchLimit(n, perf.now())); ui.lim && (ui.lim.value = agent.matchLimit); render(true); },
    status: () => ({ armed: agent.armed, paused: agent.paused, objective: agent.objective, completed: agent.completed, reason: agent.reason, replay: replay.status,
      last: agent.last, issued: !!agent.lastIssued, uiHeld: uiHeld(), patched, lastKeySent, performance: agent.performance() }),
    export: () => ({ version: 2, botVersion: '0.4.0', exportedAt: new Date().toISOString(), objective: agent.objective,
      latency: agent.latency(), performance: agent.performance(), results: agent.results.map(r => ({ ...r })), trace: agent.trace }),
    destroy: () => { send(agent.disarm(perf.now(), 'adapter destroyed')); win.clearInterval(timer); panel?.remove(); },
  };
  win.__paceBot = api;
  return api;
}


install(window);
})();
