// Bundles the ES modules into one classic script for a MAIN-world content script (no dependencies).
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const order = ['controller.mjs', 'policy.mjs', 'competitive.mjs', 'opponents.mjs', 'agent.mjs', 'replay.mjs', 'archive.mjs', 'browser.mjs'];
let body = '';
for (const f of order) {
  let s = await readFile(join(root, 'src', f), 'utf8');
  s = s.replace(/^import .*?;\s*$/gm, '').replace(/^export \{[^}]*\};?\s*$/gm, '').replace(/^export (?=(async )?(function|class|const|let))/gm, '');
  body += `// ---- src/${f}\n${s}\n`;
}
const out = `// PACE local bot — generated by tools/build.mjs from src/. Do not edit.\n(() => {\n'use strict';\n${body}\ninstall(window);\n})();\n`;
await writeFile(join(root, 'extension', 'pace-bot.js'), out);
console.log(`extension/pace-bot.js ${out.length} bytes`);
